nelmio_cors:
    defaults:
        allow_origin: ["*"] # Autorise toutes les origines
        allow_credentials: false # True si tu veux autoriser cookies/auth
        allow_headers: ["*"] # Autorise tous les headers
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"] # Toutes les m√©thodes courantes
        expose_headers: []
        max_age: 3600
    paths:
        "^/": # Toutes les routes
            allow_origin: ["*"]
            allow_headers: ["*"]
            allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
            max_age: 3600
